-- liquibase formatted sql

-- changeset lyapanov-s:1
create table protocols (
    id varchar(36),
    competition_id varchar(36) NOT NULL,
    block_3d_man8 bool DEFAULT FALSE,
    block_3d_woman8 bool DEFAULT FALSE,
    block_3d_man4 bool DEFAULT FALSE,
    block_3d_woman4 bool DEFAULT FALSE,
    block_3d_man2 bool DEFAULT FALSE,
    block_3d_woman2 bool DEFAULT FALSE,
    classic_3d_man8 bool DEFAULT FALSE,
    classic_3d_woman8 bool DEFAULT FALSE,
    classic_3d_man4 bool DEFAULT FALSE,
    classic_3d_woman4 bool DEFAULT FALSE,
    classic_3d_man2 bool DEFAULT FALSE,
    classic_3d_woman2 bool DEFAULT FALSE,
    long_3d_man8 bool DEFAULT FALSE,
    long_3d_woman8 bool DEFAULT FALSE,
    long_3d_man4 bool DEFAULT FALSE,
    long_3d_woman4 bool DEFAULT FALSE,
    long_3d_man2 bool DEFAULT FALSE,
    long_3d_woman2 bool DEFAULT FALSE,
    composite_3d_man8 bool DEFAULT FALSE,
    composite_3d_woman8 bool DEFAULT FALSE,
    composite_3d_man4 bool DEFAULT FALSE,
    composite_3d_woman4 bool DEFAULT FALSE,
    composite_3d_man2 bool DEFAULT FALSE,
    composite_3d_woman2 bool DEFAULT FALSE,
    sporting_3d_man8 bool DEFAULT FALSE,
    sporting_3d_woman8 bool DEFAULT FALSE,
    sporting_3d_man4 bool DEFAULT FALSE,
    sporting_3d_woman4 bool DEFAULT FALSE,
    sporting_3d_man2 bool DEFAULT FALSE,
    sporting_3d_woman2 bool DEFAULT FALSE,
    is_all_flags_true bool DEFAULT FALSE,
    FOREIGN KEY (competition_id) REFERENCES competitions (id)
)